### ISSUE TITLE
& Character and Speed

### ISSUE THREAD

**Issue by Wymon787** [Janik313/EnergyAirBot2021#1]
When i tried the script the row 20 and 44 didnt work. I changed the answers to "Lo &amp; Leduc" and "Tinu &amp; Dänu"

Then it worked for me. I also set up the Speed from 1500 to 200.

Thx for your Work :-)

**Comment by Janik313** [comment]
Could you please make a push request with your version?

**Comment by Janik313** [comment]
I fixed this issue in the last update.
