### ISSUE TITLE
Funktion und Änderung

### ISSUE THREAD

**Issue by luc1234512345** [Janik313/EnergyAirBot2021#4]
Hallo 

Ich wollte fragen ob du mit dem Script schon erfolg hattest und wie ich ändern kann welches Icon angeklickt wird. Weil ich weiss nicht ob ich jemals gewinnen werde wenn ich immer nur oben links klicke. Vielen Dank für deine schnelle Rückmeldung. Sonst sehr gut Programmiert.

**Comment by Janik313** [comment]
Mit diesem Skript wurde schon ein paar mal gewonnen, jedoch benötigt man doch noch etwas Glück da nur 150 mal pro Tag zwei Tickets verlost werden.

Es sollte eigentlich auch egal sein welches icon man anklickt, aber ich hab trotzdem kurz einmal eine random Funktion eingebaut. Update also mal das Skript, dann wird das Icon zufällig ausgewählt.
